http:
  port: 8080
admin:
  port: 9876
  host: localhost
serviceEndpoints: #inbound routes - list of urls you want to intercept.
  inboundRoute1: 
    url: '<your url here>'

apiEndpoints:
  inboundPath1: #inbound endpoint - list of endpoints you want to intercept.
    host: '*'
    paths: ['<inbound api endpoints>']

policies:
  - proxy
  - skyflow-api
pipelines:

  pipeline1:
    apiEndpoints:
      - inboundPath1
    policies:

          - skyflow-api:
              - action:
                  search: 
                    searchField : primary_email # field name in skyflow
                    searchKey : <field name in payload> # field name in payload
                    dlp: TOKEN #policy enforcement in the data to be sent to inbound API
                    tableName: customers
                    workspaceUrl: <your workspace Url>
                    vaultId: <your vault id>
                    serviceAccountFile: './credentials.json'

          - proxy:
              - action:
                  serviceEndpoint: inboundRoute1
              
                  
 